config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'urls#index'
  get '/:slug', to: 'urls#navigate'
  get '/a/:slug', to: 'admin#show'
  patch '/a/:slug', to: 'admin#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
    validates :long_url, presence: true
    validate :long_url_must_be_valid

    scope :active, ->() { where(active: true) }

    before_validation do |url|
        if url.long_url !~ /^http:\/\//
            url.long_url = "http://#{url.long_url}"
        end
    end

    after_create do |url|
        url.admin_slug ||= slug + RandomString.generate
        url.save
    end

    def slug
        return nil if id.nil?
        Base52Encoder.encode(id)
    end

    def self.find_by_slug(slug)
        id = Base52Encoder.decode(slug)
        find_by_id(id)
    end

    private

    def long_url_must_be_valid
        if !UrlValidator.validate(long_url)
            errors.add(:long_url, 'must be a valid url')
        end
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :set_url, only: [:show, :update]

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { render :show, notice: 'Url was successfully updated.' }
      else
        format.html { render :show }
      end
    end
  end
    
    private

    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find_by_admin_slug(params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def navigate
    slug = params[:slug]
    url = Url.active.find_by_slug(slug)
    if url
      url.num_clicks += 1
      url.save
      redirect_to url.long_url
    else
      head 404
    end
  end

  # GET /urls
  # GET /urls.json
  def index
    @url = Url.new
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to "/a/#{@url.admin_slug}", notice: 'Url was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:long_url, :active)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/admin/show.html.erb
<p id="notice"><%= notice %></p>

<%= form_with(model: @url, url: { action: "update" }, local: true) do |form| %>
  <% if @url.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <p>Uh oh! Looks like you have <%= pluralize(@url.errors.count, "error") %>!
      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="alert alert-primary">
    <div class="row">
      Your URL goes to: <%= link_to @url.long_url, @url.long_url %>
    </div>

    <div class="row">
      <% short_url = "#{root_url}#{@url.slug}" %>
      The shortened URL is: <a href="<%= short_url %>"><%= short_url %></a>
    </div>

    <div class="row">
      <% admin_url = "#{root_url}a/#{@url.admin_slug}" %>
      You can administrate this URL at: <a href="<%= admin_url %>"><%= admin_url %></a> (that's this URL!)
    </div>
  </div>

  <div>
    Your link has been clicked on: <%= @url.num_clicks %> time/s
  </div>

  <div>
    Your url is: <%= form.check_box :active %> <%= @url.active ? "active" : "inactive" %>
  </div>

  <%= form.submit class: 'update-url'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h2>URL Shortener</h2>
      <%= yield %>
    </div>
  </body>
</html>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_with(model: @url, local: true) do |form| %>
  <% if @url.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <p>Uh oh! Looks like you have <%= pluralize(@url.errors.count, "error") %>!
      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= form.text_field :long_url, class: 'col-lg-7' %>
    <%= form.submit "Shorten it!", class: 'col-lg-2 offset-md-1' %>
  </div>
<% end %>